- name: Create WordPress configuration from template
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: "{{ wordpress_install_dir }}/wordpress/wp-config.php"
    mode: "0644"

- name: Change ownership of configuration file
  ansible.builtin.file:
    path: "{{ wordpress_install_dir }}/wordpress/wp-config.php"
    owner: "{{ wordpress_web_user }}"
    group: "{{ wordpress_web_group }}"
    mode: "0640"
