- name: Download WordPress
  ansible.builtin.get_url:
    url: "{{ wordpress_download_url }}"
    dest: /tmp/wordpress.zip
    mode: "0644"

- name: Unzip WordPress
  ansible.builtin.command: unzip /tmp/wordpress.zip -d /var/www/html

- name: Change ownership of WordPress directory
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    mode: "0755"
