# SPDX-License-Identifier: MIT
---
- name: Update package lists (Debian)
  ansible.builtin.apt:
    update_cache: true
    state: present
  when: ansible_facts["os_family"] == 'Debian'

- name: Update package lists (RedHat)
  ansible.builtin.dnf:
    update_cache: true
    state: present
  when: ansible_facts["os_family"] == 'RedHat'
